# Generated by Django 2.1.1 on 2019-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Im', models.CharField(max_length=15, verbose_name='Имя')),
                ('Otch', models.CharField(max_length=20, verbose_name='Отчество')),
                ('Numm', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
        ),
    ]
