# Generated by Django 2.1.2 on 2019-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=15, verbose_name='Заголовок')),
                ('Description', models.CharField(max_length=120, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dolzhnost', models.CharField(max_length=15, verbose_name='Должность')),
                ('Stazh', models.CharField(max_length=120, verbose_name='Стаж')),
                ('tel', models.CharField(max_length=15, verbose_name='Телефон')),
                ('Fam', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Im', models.CharField(max_length=15, verbose_name='Имя')),
                ('Otch', models.CharField(max_length=20, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=15, verbose_name='Заголовок')),
                ('Description', models.CharField(max_length=120, verbose_name='Описание')),
                ('Price', models.CharField(max_length=7, verbose_name='Цена')),
            ],
        ),
    ]
