# Generated by Django 2.1.2 on 2019-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_content_doctor_servers'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Im', models.CharField(max_length=15, verbose_name='Имя')),
                ('Otch', models.CharField(max_length=20, verbose_name='Отчество')),
                ('Numm', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('Dolj', models.CharField(max_length=15, verbose_name='Должность')),
                ('StajR', models.CharField(max_length=15, verbose_name='должность')),
            ],
        ),
    ]
