# Generated by Django 2.1.1 on 2019-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Passw',
            field=models.CharField(default=1, max_length=50, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
