# Generated by Django 2.1.2 on 2019-01-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.client')),
                ('servies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.servers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user')),
            ],
        ),
    ]
