# Generated by Django 2.1.2 on 2019-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Ссылка картинки'),
        ),
    ]
