# Generated by Django 2.1.2 on 2019-01-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_user_img'),
        ('clinic', '0004_user_passw'),
    ]

    operations = [
    ]
