# Generated by Django 2.1.1 on 2019-01-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_merge_20190122_1138'),
        ('clinic', '0006_merge_20190122_0833'),
    ]

    operations = [
    ]
