# Generated by Django 2.1.1 on 2019-01-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_merge_20190122_1244'),
        ('clinic', '0006_merge_20190122_0826'),
    ]

    operations = [
    ]
