# Generated by Django 2.1.1 on 2019-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20190123_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('V', 'Врач'), ('S', 'Секретарь')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
