# Generated by Django 2.1.2 on 2019-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
