# Generated by Django 2.1.2 on 2019-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20190124_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='username',
        ),
    ]
