# Generated by Django 2.1.2 on 2019-01-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20190124_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Img',
        ),
    ]
