# Generated by Django 2.1.2 on 2019-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20190124_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dolzhnost', models.CharField(max_length=15, verbose_name='Должность')),
                ('Stazh', models.CharField(max_length=120, verbose_name='Стаж')),
                ('tel', models.CharField(max_length=15, verbose_name='Телефон')),
                ('Fam', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Im', models.CharField(max_length=15, verbose_name='Имя')),
                ('Otch', models.CharField(max_length=20, verbose_name='Отчество')),
            ],
        ),
    ]
