# Generated by Django 2.1.2 on 2019-01-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_doctor'),
        ('clinic', '0011_auto_20190124_1130'),
    ]

    operations = [
    ]
