# Generated by Django 2.1.1 on 2019-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20190125_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='servies',
        ),
        migrations.AddField(
            model_name='visit',
            name='Numm',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
